paths:
    /place/{type}:
        get:
            tags:
                - Place
            summary: 다양한 장소 목록 조회 (카페, 한식, 중식, 일식, 팝업 등)
            parameters:
                - name: type
                  in: path
                  required: true
                  description: 조회할 장소 유형 (korean, chinese, japanese, western, expert_cafe, dessert_cafe, popup, jazzbar, movie)
                  schema:
                      type: string
                      enum: [korean, chinese, japanese, cafe, popup]
            responses:
                '200':
                    description: 성공적으로 장소 목록을 조회했습니다.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    isSuccess:
                                        type: boolean
                                        example: true
                                    code:
                                        type: integer
                                        example: 2000
                                    message:
                                        type: string
                                        example: 'SUCCESS!'
                                    result:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                name:
                                                    type: string
                                                    example: '해피 샤오관'
                                                place_type:
                                                    type: string
                                                    example: '중식'
                                                address1:
                                                    type: string
                                                    example: '서울 광진구 동일로18길 91'
                                                address2:
                                                    type: string
                                                    example: '자양동 6-19'
                                                rating:
                                                    type: integer
                                                    example: 5
                                                numberofscore:
                                                    type: string
                                                    example: '2건'
                                                review:
                                                    type: string
                                                    example: '리뷰 0'
                                                hour:
                                                    type: string
                                                    example: '영업시간 매일 11:00 ~ 23:00'
                                                phone_number:
                                                    type: string
                                                    example: '0507-1324-9354'
                                                moreview_link:
                                                    type: string
                                                    format: uri
                                                    example: 'https://place.map.kakao.com/1130688627'
                                                homepage_link:
                                                    type: string
                                                    format: uri
                                                    example: 'https://map.kakao.com/#none'
                '400':
                    description: 잘못된 요청
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 400
                                    isSuccess:
                                        type: boolean
                                        example: false
                                    code:
                                        type: string
                                        example: 'COMMON001'
                                    message:
                                        type: string
                                        example: '잘못된 요청입니다'
                '500':
                    description: 서버 에러
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        example: 500
                                    isSuccess:
                                        type: boolean
                                        example: false
                                    code:
                                        type: string
                                        example: 'COMMON000'
                                    message:
                                        type: string
                                        example: '서버 에러, 관리자에게 문의 바랍니다.'
